# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "CGBOX"
subtitle: "Arch Viz"
author: "Cg Box"
header:
 title: "Arch Viz"
 subtitle: "Cg Box"
footer:
 name: "Hey there"
 bio: "Teste "
 #github: ""
web_design: "lucas "
social_urls:
  facebook: "link para o FB"
  twitter: "Link para o twitter" 
  instagram: "Link para o instagram"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
